// <auto-generated />
using System;
using MediCheck.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediCheck.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260622202652_AddLieuLuongTheoNhomTuoiTable")]
    partial class AddLieuLuongTheoNhomTuoiTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MediCheck.Api.Models.GioiHanTuoiThuoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LyDo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MucDo")
                        .HasColumnType("int");

                    b.Property<int>("ThuocId")
                        .HasColumnType("int");

                    b.Property<int>("TuoiDen")
                        .HasColumnType("int");

                    b.Property<int>("TuoiTu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ThuocId");

                    b.ToTable("GioiHanTuoiThuoc");
                });

            modelBuilder.Entity("MediCheck.Api.Models.LieuLuongTheoNhomTuoi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("LieuLuongKhuyenNghi")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ThuocId")
                        .HasColumnType("int");

                    b.Property<int>("TuoiDen")
                        .HasColumnType("int");

                    b.Property<int>("TuoiTu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ThuocId");

                    b.ToTable("LieuLuongTheoNhomTuoi");
                });

            modelBuilder.Entity("MediCheck.Api.Models.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("MaXacThucResetPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetPasswordExpiry")
                        .HasColumnType("datetime2");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<int>("VaiTro")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("MediCheck.Api.Models.NhomThuoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenNhomThuoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("NhomThuoc");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TenNhomThuoc = "Giảm đau - Hạ sốt"
                        },
                        new
                        {
                            Id = 2,
                            TenNhomThuoc = "Kháng sinh"
                        },
                        new
                        {
                            Id = 3,
                            TenNhomThuoc = "Kháng viêm"
                        },
                        new
                        {
                            Id = 4,
                            TenNhomThuoc = "Dị ứng - Kháng Histamin"
                        },
                        new
                        {
                            Id = 5,
                            TenNhomThuoc = "Tiêu hoá"
                        });
                });

            modelBuilder.Entity("MediCheck.Api.Models.QuyenEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MaQuyen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Quyen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaQuyen = "THUOC_XEM",
                            Module = "DanhMucThuoc",
                            TenQuyen = "Xem danh mục thuốc"
                        },
                        new
                        {
                            Id = 2,
                            MaQuyen = "THUOC_QUANLY",
                            Module = "DanhMucThuoc",
                            TenQuyen = "Thêm/Sửa/Xoá thuốc"
                        },
                        new
                        {
                            Id = 3,
                            MaQuyen = "KIEMTRA_THUOC",
                            Module = "KiemTra",
                            TenQuyen = "Kiểm tra thuốc theo độ tuổi"
                        },
                        new
                        {
                            Id = 4,
                            MaQuyen = "BENHNHAN_XEM",
                            Module = "BenhNhan",
                            TenQuyen = "Xem hồ sơ bệnh nhân"
                        },
                        new
                        {
                            Id = 5,
                            MaQuyen = "BENHNHAN_QUANLY",
                            Module = "BenhNhan",
                            TenQuyen = "Thêm/Sửa hồ sơ bệnh nhân"
                        },
                        new
                        {
                            Id = 6,
                            MaQuyen = "TAIKHOAN_QUANLY",
                            Module = "TaiKhoan",
                            TenQuyen = "Quản lý tài khoản người dùng"
                        },
                        new
                        {
                            Id = 7,
                            MaQuyen = "BAOCAO_XEM",
                            Module = "BaoCao",
                            TenQuyen = "Xem báo cáo & thống kê"
                        });
                });

            modelBuilder.Entity("MediCheck.Api.Models.Thuoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DangBaoChe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("DangSuDung")
                        .HasColumnType("bit");

                    b.Property<string>("GhiChuChongChiDinh")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HamLuong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HoatChatChinh")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LieuLuongKhuyenNghi")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("MaThuoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NhomThuocId")
                        .HasColumnType("int");

                    b.Property<string>("TenThuoc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TuoiApDungDen")
                        .HasColumnType("int");

                    b.Property<int>("TuoiApDungTu")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaThuoc")
                        .IsUnique();

                    b.HasIndex("NhomThuocId");

                    b.ToTable("Thuoc");
                });

            modelBuilder.Entity("MediCheck.Api.Models.VaiTroEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("VaiTroDanhSach");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MoTa = "Quản trị viên hệ thống",
                            TenVaiTro = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            MoTa = "Bác sĩ",
                            TenVaiTro = "BacSi"
                        },
                        new
                        {
                            Id = 3,
                            MoTa = "Dược sĩ",
                            TenVaiTro = "DuocSi"
                        });
                });

            modelBuilder.Entity("MediCheck.Api.Models.VaiTroQuyen", b =>
                {
                    b.Property<int>("VaiTroId")
                        .HasColumnType("int");

                    b.Property<int>("QuyenId")
                        .HasColumnType("int");

                    b.HasKey("VaiTroId", "QuyenId");

                    b.HasIndex("QuyenId");

                    b.ToTable("VaiTroQuyen");

                    b.HasData(
                        new
                        {
                            VaiTroId = 1,
                            QuyenId = 1
                        },
                        new
                        {
                            VaiTroId = 1,
                            QuyenId = 2
                        },
                        new
                        {
                            VaiTroId = 1,
                            QuyenId = 3
                        },
                        new
                        {
                            VaiTroId = 1,
                            QuyenId = 4
                        },
                        new
                        {
                            VaiTroId = 1,
                            QuyenId = 5
                        },
                        new
                        {
                            VaiTroId = 1,
                            QuyenId = 6
                        },
                        new
                        {
                            VaiTroId = 1,
                            QuyenId = 7
                        },
                        new
                        {
                            VaiTroId = 2,
                            QuyenId = 1
                        },
                        new
                        {
                            VaiTroId = 2,
                            QuyenId = 3
                        },
                        new
                        {
                            VaiTroId = 2,
                            QuyenId = 4
                        },
                        new
                        {
                            VaiTroId = 2,
                            QuyenId = 5
                        },
                        new
                        {
                            VaiTroId = 2,
                            QuyenId = 7
                        },
                        new
                        {
                            VaiTroId = 3,
                            QuyenId = 1
                        },
                        new
                        {
                            VaiTroId = 3,
                            QuyenId = 2
                        },
                        new
                        {
                            VaiTroId = 3,
                            QuyenId = 3
                        },
                        new
                        {
                            VaiTroId = 3,
                            QuyenId = 4
                        });
                });

            modelBuilder.Entity("MediCheck.Api.Models.GioiHanTuoiThuoc", b =>
                {
                    b.HasOne("MediCheck.Api.Models.Thuoc", "Thuoc")
                        .WithMany()
                        .HasForeignKey("ThuocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thuoc");
                });

            modelBuilder.Entity("MediCheck.Api.Models.LieuLuongTheoNhomTuoi", b =>
                {
                    b.HasOne("MediCheck.Api.Models.Thuoc", "Thuoc")
                        .WithMany()
                        .HasForeignKey("ThuocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thuoc");
                });

            modelBuilder.Entity("MediCheck.Api.Models.Thuoc", b =>
                {
                    b.HasOne("MediCheck.Api.Models.NhomThuoc", "NhomThuoc")
                        .WithMany()
                        .HasForeignKey("NhomThuocId");

                    b.Navigation("NhomThuoc");
                });

            modelBuilder.Entity("MediCheck.Api.Models.VaiTroQuyen", b =>
                {
                    b.HasOne("MediCheck.Api.Models.QuyenEntity", "Quyen")
                        .WithMany("VaiTroQuyens")
                        .HasForeignKey("QuyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MediCheck.Api.Models.VaiTroEntity", "VaiTro")
                        .WithMany("VaiTroQuyens")
                        .HasForeignKey("VaiTroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quyen");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("MediCheck.Api.Models.QuyenEntity", b =>
                {
                    b.Navigation("VaiTroQuyens");
                });

            modelBuilder.Entity("MediCheck.Api.Models.VaiTroEntity", b =>
                {
                    b.Navigation("VaiTroQuyens");
                });
#pragma warning restore 612, 618
        }
    }
}
